---
- name: Wordpress 
  hosts: 54.245.22.189
  become: yes
  become_method: sudo
  tasks:
    - name: packages installation
      package:
        name: "{{item}}"
        state: latest
      with_items:
       - epel-release
       - wget 
       - unzip
       - mysql-server
      ignore_errors: true

    - name: epel-release installation 
      shell: "sudo yum install http://rpms.remirepo.net/enterprise/remi-release-6.rpm -y"
    - name: config manager enabled 
      shell: "sudo yum-config-manager --enable remi-php72"
    - name : update httpd PHP 
      shell: "sudo yum install httpd php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql mysql -y" 

    - name:  wordpress download
      get_url:
        url: https://wordpress.org/wordpress-5.2.1.tar.gz
        dest: /tmp/

    - name: Unzip wordpress file
      unarchive:
        src: "/tmp/wordpress-5.2.1.tar.gz"    
        dest: "/var/www/html"
        remote_src: yes
      become: yes
      become_method: sudo

    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted  
        enabled: yes
      become: yes
      become_method: sudo
